# Generated by Django 4.1.5 on 2023-05-24 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='App_secret_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
